services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:v1
    container_name: mariadb
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p\"$$(cat /run/secrets/db_root_password)\" --silent"]
      interval: 3s
      timeout: 3s
      retries: 30
    networks:
      - inception
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:v1
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --path=/var/www/html --allow-root && php -r 'exit(@fsockopen(\"127.0.0.1\", 9000) ? 0 : 1);'"]
      interval: 5s
      timeout: 5s
      retries: 40
    networks:
      - inception
    secrets:
      - db_password
      - wp_password_admin
      - wp_password_user
    volumes:
      - wp_data:/var/www/html

  nginx:
    build: ./requirements/nginx
    image: nginx:v1
    container_name: nginx
    restart: always
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy
      uptime-kuma:
        condition: service_healthy
      static-site:
        condition: service_healthy
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html

  uptime-kuma:
    build: ./requirements/bonus/uptime-kuma
    image: uptime-kuma:v1
    container_name: uptime-kuma
    restart: always
    env_file: .env
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - uptime_kuma_data:/app/data

  static-site:
    build: ./requirements/bonus/static-site
    image: static-site:v1
    container_name: static-site
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/ > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  uptime_kuma_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/uptime-kuma

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/.db_password
  db_root_password:
    file: ../secrets/.db_root_password
  wp_password_admin:
    file: ../secrets/.wp_password_admin
  wp_password_user:
    file: ../secrets/.wp_password_user
